SELECT CUSTOMER_NAME FROM TELECOM_CUSTOMER WHERE PRODUCT='Digital Subscriber Line';

SELECT CUSTOMER_ID,CUSTOMER_NAME FROM TELECOM_CUSTOMER WHERE CUSTOMER_NAME LIKE 'sa%';

SELECT CUSTOMER_ID,CUSTOMER_NAME FROM TELECOM_CUSTOMER WHERE CUSTOMER_SEGMENT='Gold';

SELECT PRODUCT,COUNT(PRODUCT) FROM TELECOM_CUSTOMER GROUP BY PRODUCT;

SELECT CUSTOMER_NAME FROM TELECOM_CUSTOMER WHERE ZONE='Mountain';