/*1. WRITE A SQL QUERY TO LIST OF CUSTOMER NAMES WHO ARE USING PRODUCT DIGITAL SUBSCRIBER LINE?*/
SELECT "Customer Name" FROM TELECOM
WHERE PRODUCT='Digital Subscriber Line';

/* 2. WRITE A SQL QUERY TO LIST CUSTOMER_ID AND NAME LIKE SA? */
SELECT CUSTOMER_ID,"Customer Name" FROM TELECOM
WHERE "Customer Name" LIKE 'sa%';

/*3.WRITE SQL QUERY TO LIST THE CUSTOMER IDS AND NAMES FOR CUSTOMERS BELONGING TO THE GOLD CUSTOMER SEGMENT.*/
SELECT CUSTOMER_ID,"Customer Name" FROM TELECOM
WHERE "Service Segment"='Gold';

/*4 WRITE A SQL QUERY TO COUNT THE CUSTOMER LIST PRODUCT WISE*/
SELECT PRODUCT,COUNT(PRODUCT) FROM TELECOM GROUP BY PRODUCT;

/*5. WRITE AN SQL QUERY TO LIST THE CUSTOMER NAME ZONE 'MOUNTAIN'*/
SELECT "Customer Name" FROM TELECOM WHERE ZONE LIKE 'M%';